project:
  type: website
  preview:
    port: 4020
    browser: false

website:
  title: "R Development" 
  repo-url: https://github.com/jjjermiah/r-development
  repo-actions: [edit, source, issue]
  navbar:
    left:
      - text: "Home"
        file: index.qmd

      - text: "Advanced R"
        href: adv-r/index.qmd
      
      - text: "R for Data Science"
        href: r4ds/index.qmd

      - text: "Package Dev"
        href: r-pkgs/index.qmd

      - text: "Production Engineering"
        href: r-production/index.qmd

      - text: "Shiny"
        href: shiny/index.qmd

      - text: "Modelling"
        href: modelling/index.qmd

  sidebar:
    - id: r4ds
      title: "R for Data Science"
      href: r4ds/index.qmd
      contents: r4ds
    
    - id: adv-r
      title: "Advanced R"
      contents: adv-r
    
    - id: r-pkgs
      title: "Package Dev"
      contents: r-pkgs
    
    - id: r-production
      title: "Production Engineering"
      contents: r-production
    
    - id: shiny
      title: "Shiny"
      contents: shiny

    - id: modelling
      title: "Modelling"
      contents: modelling

  page-navigation: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



