project:
  type: website
  preview:
    port: 4020
    browser: false

website:
  title: "R Development" 
  repo-url: https://github.com/jjjermiah/r-development
  repo-actions: [edit, source, issue]
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:r4ds
      - text: "Advanced R"
        href: adv-r/index.qmd
        
      # - sidebar:adv-r
      - sidebar:r-pkgs
      - sidebar:r-production
      - sidebar:shiny
      - sidebar:modelling
  

  sidebar:
    - id: r4ds
      title: "R for Data Science"
      href: r4ds/index.qmd
      contents: r4ds
    
    - id: adv-r
      title: "Advanced R"

      contents: 
        - adv-r/index.qmd
        - adv-r/01-wrangle.qmd
    
    - id: r-pkgs
      title: "Package Dev"
      contents: r-pkgs
    
    - id: r-production
      title: "Production Engineering"
      contents: r-production
    
    - id: shiny
      title: "Shiny"
      contents: shiny

    - id: modelling
      title: "Modelling"
      contents: modelling

  page-navigation: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



